### ISSUE TITLE
Create a ReadMe

### ISSUE THREAD

**Issue by muydanny** [Initiate-Colorado/initiate-co-ui#24]
Create a comprehensive ReadMe where a developer could follow along our initial outline, setup, and process of creating/developing the application.

- [ ] Phase 1

- [ ] Phase 2 

- [ ] Phase 3

**Comment by anshdhinhgra47** [comment]
I would like to take up this issue. Could you please let me know your requirements ?

**Comment by muydanny** [comment]
Hey @anshdhinhgra47 thanks for the interest. However, at this moment this is a private project.

**Comment by anshdhinhgra47** [comment]
No problem. I understand.
